// apps/react/src/pages/Challenges.tsx
import ChallengeGrid from '@/components/challenges/ChallengeGrid';
import Navbar from '@/components/navbar/Navbar';
import ScrollBtn from '@/components/scroll-to-top/ScrollBtn';

function App() {
  return (
    <>
      <Navbar>
        <a href="/fmc/javascript/">JavaScript Mini Challenges</a>
        <a href="/fmc/vue/">VueJs Mini Challenges</a>
      </Navbar>

      <div className="container text-center">
        <ChallengeGrid />
        <ScrollBtn />
      </div>
    </>
  );
}

export default App;

// apps/vue/src/pages/challenges.vue
<template>
  <Navbar>
    <a href="/fmc/javascript">JavaScript Mini Challenges</a>
    <a href="/fmc/react/">React Mini Challenges</a>
  </Navbar>

  <div className="container text-center">
    <ChallengeGrid />
  </div>
</template>

<script setup lang="ts">
import ChallengeGrid from '@/components/ChallengeGrid.vue';
import Navbar from '@/components/Navbar.vue';
</script>
